fastlane_require 'yaml'

default_platform(:ios)

platform :ios do

  desc "Run lint on the code"
  lane :lint do
    swiftlint(
      mode: :lint,
      config_file: ".swiftlint.yml", 
      output_file: "fastlane/lint_output/lint_output.json",
      raise_if_swiftlint_error: true
    )
  end

  desc "Run all Unit Tests"
  lane :test do
    scan(scheme: "WeatherExplorerTests")
  end

  desc "Run all UI Tests"
  lane :ui_test do
    scan(scheme: "WeatherExplorerUITests", reset_simulator: true, disable_concurrent_testing: true)
  end
end